// alphabetized national parks by State
const listOfParks = {
	Alaska: [
		'Denali National Park',
		'Gates of the Arctic National Park',
		'Glacier Bay National Park',
		'Katmai National Park',
		'Kenai Fjords National Park',
		'Kobuk Valley National Park',
		'Lake Clark National Park',
		'Wrangell-St. Elias National Park',
	],
	'American Samoa': ['National Park of American Samoa'],
	Arizona: [
		'Grand Canyon National Park',
		'Petrified Forest National Park',
		'Saguaro National Park',
	],
	Arkansas: ['Hot Springs National Park'],
	California: [
		'Channel Islands National Park',
		'Death Valley National Park',
		'Joshua Tree National Park',
		'Kings Canyon National Park',
		'Lassen Volcanic National Park',
		'Pinnacles National Park',
		'Redwood National Park',
		'Sequoia National Park',
		'Yosemite National Park',
	],
	Colorado: [
		'Black Canyon of the Gunnison National Park',
		'Great Sand Dunes National Park',
		'Mesa Verde National Park',
		'Rocky Mountain National Park',
	],
	Florida: [
		'Biscayne National Park',
		'Dry Tortugas National Park',
		'Everglades National Park',
	],
	Hawaii: ['Haleakala National Park', 'Hawai’i Volcanoes National Park'],
	'Idaho, Montana, Wyoming': ['Yellowstone National Park'],
	Kentucky: ['Mammoth Cave National Park'],
	Indiana: ['Indiana Dunes National Park'],
	Maine: ['Acadia National Park'],
	Michigan: ['Isle Royale National Park'],
	Minnesota: ['Voyageurs National Park'],
	Missouri: ['Gateway Arch National Park'],
	Montana: ['Glacier National Park'],
	Nevada: ['Great Basin National Park'],
	'New Mexico': ['Carlsbad Caverns National Park', 'White Sands National Park'],
	'North Dakota': ['Theodore Roosevelt National Park'],
	'North Carolina, Tennessee': ['Great Smoky Mountains National Park'],
	Ohio: ['Cuyahoga Valley National Park'],
	Oregon: ['Crater Lake National Park'],
	'South Carolina': ['Congaree National Park'],
	'South Dakota': ['Badlands National Park', 'Wind Cave National Park'],
	Texas: ['Big Bend National Park', 'Guadalupe Mountains National Park'],
	Utah: [
		'Arches National Park',
		'Bryce Canyon National Park',
		'Canyonlands National Park',
		'Capitol Reef National Park',
		'Zion National Park',
	],
	'Virgin Islands': ['Virgin Islands National Park'],
	Virginia: ['Shenandoah National Park'],
	Washington: [
		'Mount Rainier National Park',
		'North Cascades National Park',
		'Olympic National Park',
	],
	'West Virginia': ['New River Gorge National Park'],
	Wyoming: ['Grand Teton National Park'],
};

export default listOfParks;
